export { default as Mouse } from './manual'
export { default as Still } from './still'
export { default as Random } from './random'
export { default as Scared } from './scared'
export { default as Agile } from './agile'
